version: '3'
services:
  next:
    build: .
    volumes:
      - .:/usr/src/app
    command: bash -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    networks:
      - sail
networks:
  sail:
    external:
      name: skill-climb_sail
